
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Newtonsoft.Json.Linq;



namespace cfg.main
{

public sealed partial class ChActionNumericConfig : Luban.BeanBase
{
    public ChActionNumericConfig(JToken _buf) 
    {
        JObject _obj = _buf as JObject;
        ActionId = (int)_obj.GetValue("action_id");
        EnergyCost = (float)_obj.GetValue("energy_cost");
    }

    public static ChActionNumericConfig DeserializeChActionNumericConfig(JToken _buf)
    {
        return new main.ChActionNumericConfig(_buf);
    }

    /// <summary>
    /// 动作id
    /// </summary>
    public readonly int ActionId;
    /// <summary>
    /// 能量消耗
    /// </summary>
    public readonly float EnergyCost;


    public const int __ID__ = -2022051105;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "actionId:" + ActionId + ","
        + "energyCost:" + EnergyCost + ","
        + "}";
    }
}
}

