
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Newtonsoft.Json.Linq;



namespace cfg.main
{

public sealed partial class ChBaseAttrConfig : Luban.BeanBase
{
    public ChBaseAttrConfig(JToken _buf) 
    {
        JObject _obj = _buf as JObject;
        AttrType = (main.EAttrType)(int)_obj.GetValue("attr_type");
        Value = (float)_obj.GetValue("value");
    }

    public static ChBaseAttrConfig DeserializeChBaseAttrConfig(JToken _buf)
    {
        return new main.ChBaseAttrConfig(_buf);
    }

    public readonly main.EAttrType AttrType;
    public readonly float Value;


    public const int __ID__ = 412127678;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "attrType:" + AttrType + ","
        + "value:" + Value + ","
        + "}";
    }
}
}

