
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Newtonsoft.Json.Linq;



namespace cfg.main
{

public sealed partial class ChHitNumericConfig : Luban.BeanBase
{
    public ChHitNumericConfig(JToken _buf) 
    {
        JObject _obj = _buf as JObject;
        HitId = (int)_obj.GetValue("hit_id");
        DmgMult = (float)_obj.GetValue("dmg_mult");
        DazeMult = (float)_obj.GetValue("daze_mult");
        Element = (int)_obj.GetValue("element");
        Comment = (string)_obj.GetValue("comment");
    }

    public static ChHitNumericConfig DeserializeChHitNumericConfig(JToken _buf)
    {
        return new main.ChHitNumericConfig(_buf);
    }

    public readonly int HitId;
    /// <summary>
    /// 伤害倍率
    /// </summary>
    public readonly float DmgMult;
    /// <summary>
    /// 失衡倍率
    /// </summary>
    public readonly float DazeMult;
    public readonly int Element;
    public readonly string Comment;


    public const int __ID__ = -1738831658;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "hitId:" + HitId + ","
        + "dmgMult:" + DmgMult + ","
        + "dazeMult:" + DazeMult + ","
        + "element:" + Element + ","
        + "comment:" + Comment + ","
        + "}";
    }
}
}

