
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Newtonsoft.Json.Linq;



namespace cfg.main
{

public sealed partial class CurrencyItemConfig : Luban.BeanBase
{
    public CurrencyItemConfig(JToken _buf) 
    {
        JObject _obj = _buf as JObject;
        Id = (int)_obj.GetValue("id");
        Name = (string)_obj.GetValue("name");
        IconLoc = (string)_obj.GetValue("icon_loc");
        Desc = (string)_obj.GetValue("desc");
    }

    public static CurrencyItemConfig DeserializeCurrencyItemConfig(JToken _buf)
    {
        return new main.CurrencyItemConfig(_buf);
    }

    public readonly int Id;
    /// <summary>
    /// 名称
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 图标位置
    /// </summary>
    public readonly string IconLoc;
    /// <summary>
    /// 描述
    /// </summary>
    public readonly string Desc;


    public const int __ID__ = -1036530277;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "name:" + Name + ","
        + "iconLoc:" + IconLoc + ","
        + "desc:" + Desc + ","
        + "}";
    }
}
}

