
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Newtonsoft.Json.Linq;



namespace cfg.main
{

public sealed partial class DialogueOptionConfig : Luban.BeanBase
{
    public DialogueOptionConfig(JToken _buf) 
    {
        JObject _obj = _buf as JObject;
        NextSubCid = (int)_obj.GetValue("next_sub_cid");
        Content = (string)_obj.GetValue("content");
        ClickCmd = (string)_obj.GetValue("click_cmd");
        Arg1 = (string)_obj.GetValue("arg1");
        Arg2 = (string)_obj.GetValue("arg2");
        Arg3 = (string)_obj.GetValue("arg3");
    }

    public static DialogueOptionConfig DeserializeDialogueOptionConfig(JToken _buf)
    {
        return new main.DialogueOptionConfig(_buf);
    }

    public readonly int NextSubCid;
    public readonly string Content;
    public readonly string ClickCmd;
    public readonly string Arg1;
    public readonly string Arg2;
    public readonly string Arg3;


    public const int __ID__ = 910458692;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "nextSubCid:" + NextSubCid + ","
        + "content:" + Content + ","
        + "clickCmd:" + ClickCmd + ","
        + "arg1:" + Arg1 + ","
        + "arg2:" + Arg2 + ","
        + "arg3:" + Arg3 + ","
        + "}";
    }
}
}

