
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Newtonsoft.Json.Linq;



namespace cfg.main
{

public sealed partial class DialogueGraphOptionConfig : Luban.BeanBase
{
    public DialogueGraphOptionConfig(JToken _buf) 
    {
        JObject _obj = _buf as JObject;
        Cid = (int)_obj.GetValue("cid");
        { var __json0 = _obj.GetValue("optionsList"); OptionsList = new System.Collections.Generic.List<main.DialogueOptionsConfig>((__json0 as JArray).Count); foreach(JToken __e0 in __json0) { main.DialogueOptionsConfig __v0;  __v0 = main.DialogueOptionsConfig.DeserializeDialogueOptionsConfig(__e0);  OptionsList.Add(__v0); }   }
    }

    public static DialogueGraphOptionConfig DeserializeDialogueGraphOptionConfig(JToken _buf)
    {
        return new main.DialogueGraphOptionConfig(_buf);
    }

    public readonly int Cid;
    public readonly System.Collections.Generic.List<main.DialogueOptionsConfig> OptionsList;


    public const int __ID__ = 265821560;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        foreach (var _e in OptionsList) { _e?.ResolveRef(tables); }
    }

    public override string ToString()
    {
        return "{ "
        + "cid:" + Cid + ","
        + "optionsList:" + Luban.StringUtil.CollectionToString(OptionsList) + ","
        + "}";
    }
}
}

