
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Newtonsoft.Json.Linq;



namespace cfg.main
{

public sealed partial class DialogueSentenceConfig : Luban.BeanBase
{
    public DialogueSentenceConfig(JToken _buf) 
    {
        JObject _obj = _buf as JObject;
        SubCid = (int)_obj.GetValue("sub_cid");
        NextSubCid = (int)_obj.GetValue("next_sub_cid");
        Name = (string)_obj.GetValue("name");
        Content = (string)_obj.GetValue("content");
        ExitCmd = (string)_obj.GetValue("exit_cmd");
        Arg1 = (string)_obj.GetValue("arg1");
        Arg2 = (string)_obj.GetValue("arg2");
        Arg3 = (string)_obj.GetValue("arg3");
    }

    public static DialogueSentenceConfig DeserializeDialogueSentenceConfig(JToken _buf)
    {
        return new main.DialogueSentenceConfig(_buf);
    }

    public readonly int SubCid;
    public readonly int NextSubCid;
    public readonly string Name;
    public readonly string Content;
    public readonly string ExitCmd;
    public readonly string Arg1;
    public readonly string Arg2;
    public readonly string Arg3;


    public const int __ID__ = 1309346674;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "subCid:" + SubCid + ","
        + "nextSubCid:" + NextSubCid + ","
        + "name:" + Name + ","
        + "content:" + Content + ","
        + "exitCmd:" + ExitCmd + ","
        + "arg1:" + Arg1 + ","
        + "arg2:" + Arg2 + ","
        + "arg3:" + Arg3 + ","
        + "}";
    }
}
}

