
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Newtonsoft.Json.Linq;



namespace cfg.main
{

public sealed partial class DiscAttrEntryConfig : Luban.BeanBase
{
    public DiscAttrEntryConfig(JToken _buf) 
    {
        JObject _obj = _buf as JObject;
        Id = (int)_obj.GetValue("id");
        AttrType = (main.EAttrType)(int)_obj.GetValue("attr_type");
        SubValue = (float)_obj.GetValue("sub_value");
        MainValue = (float)_obj.GetValue("main_value");
    }

    public static DiscAttrEntryConfig DeserializeDiscAttrEntryConfig(JToken _buf)
    {
        return new main.DiscAttrEntryConfig(_buf);
    }

    public readonly int Id;
    /// <summary>
    /// 属性名称
    /// </summary>
    public readonly main.EAttrType AttrType;
    /// <summary>
    /// 位于副属性值
    /// </summary>
    public readonly float SubValue;
    /// <summary>
    /// 位于主属性值
    /// </summary>
    public readonly float MainValue;


    public const int __ID__ = 93135225;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "attrType:" + AttrType + ","
        + "subValue:" + SubValue + ","
        + "mainValue:" + MainValue + ","
        + "}";
    }
}
}

