
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Newtonsoft.Json.Linq;



namespace cfg.main
{

public sealed partial class DiscAttrEntryAppearConfig : Luban.BeanBase
{
    public DiscAttrEntryAppearConfig(JToken _buf) 
    {
        JObject _obj = _buf as JObject;
        Pos = (int)_obj.GetValue("pos");
        { var __json0 = _obj.GetValue("attr_entry_ids"); AttrEntryIds = new System.Collections.Generic.List<int>((__json0 as JArray).Count); foreach(JToken __e0 in __json0) { int __v0;  __v0 = (int)__e0;  AttrEntryIds.Add(__v0); }   }
    }

    public static DiscAttrEntryAppearConfig DeserializeDiscAttrEntryAppearConfig(JToken _buf)
    {
        return new main.DiscAttrEntryAppearConfig(_buf);
    }

    /// <summary>
    /// 7为副词条
    /// </summary>
    public readonly int Pos;
    public readonly System.Collections.Generic.List<int> AttrEntryIds;


    public const int __ID__ = -275656146;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "pos:" + Pos + ","
        + "attrEntryIds:" + Luban.StringUtil.CollectionToString(AttrEntryIds) + ","
        + "}";
    }
}
}

