
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Newtonsoft.Json.Linq;



namespace cfg.main
{

public sealed partial class DiscUpgradeExpConfig : Luban.BeanBase
{
    public DiscUpgradeExpConfig(JToken _buf) 
    {
        JObject _obj = _buf as JObject;
        Level = (int)_obj.GetValue("level");
        Exp = (int)_obj.GetValue("exp");
    }

    public static DiscUpgradeExpConfig DeserializeDiscUpgradeExpConfig(JToken _buf)
    {
        return new main.DiscUpgradeExpConfig(_buf);
    }

    public readonly int Level;
    public readonly int Exp;


    public const int __ID__ = -1417075219;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "level:" + Level + ","
        + "exp:" + Exp + ","
        + "}";
    }
}
}

