
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Newtonsoft.Json.Linq;



namespace cfg.main
{

public sealed partial class GotoQuestConfig : main.QuestConfig
{
    public GotoQuestConfig(JToken _buf)  : base(_buf) 
    {
        JObject _obj = _buf as JObject;
        Center = vector3.Deserializevector3(_obj.GetValue("center"));
        Radius = (float)_obj.GetValue("radius");
    }

    public static GotoQuestConfig DeserializeGotoQuestConfig(JToken _buf)
    {
        return new main.GotoQuestConfig(_buf);
    }

    public readonly vector3 Center;
    public readonly float Radius;


    public const int __ID__ = -17409268;
    public override int GetTypeId() => __ID__;

    public override void ResolveRef(Tables tables)
    {
        base.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "questCid:" + QuestCid + ","
        + "nextQuestCid:" + NextQuestCid + ","
        + "name:" + Name + ","
        + "desc:" + Desc + ","
        + "npcOverrides:" + Luban.StringUtil.CollectionToString(NpcOverrides) + ","
        + "completeGetQuestChainCid:" + CompleteGetQuestChainCid + ","
        + "trunkNpcCids:" + Luban.StringUtil.CollectionToString(TrunkNpcCids) + ","
        + "center:" + Center + ","
        + "radius:" + Radius + ","
        + "}";
    }
}
}

