
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Newtonsoft.Json.Linq;



namespace cfg.main
{

public sealed partial class MonsterConfig : Luban.BeanBase
{
    public MonsterConfig(JToken _buf) 
    {
        JObject _obj = _buf as JObject;
        Id = (int)_obj.GetValue("id");
        Name = (string)_obj.GetValue("name");
        Location = (string)_obj.GetValue("location");
        Hp = (float)_obj.GetValue("hp");
        Atk = (float)_obj.GetValue("atk");
        Def = (float)_obj.GetValue("def");
        MaxDaze = (float)_obj.GetValue("max_daze");
        StunDuration = (float)_obj.GetValue("stun_duration");
        StunDmgMultiplier = (float)_obj.GetValue("stun_dmg_multiplier");
        IconLoc = (string)_obj.GetValue("icon_loc");
    }

    public static MonsterConfig DeserializeMonsterConfig(JToken _buf)
    {
        return new main.MonsterConfig(_buf);
    }

    public readonly int Id;
    public readonly string Name;
    public readonly string Location;
    public readonly float Hp;
    public readonly float Atk;
    public readonly float Def;
    public readonly float MaxDaze;
    public readonly float StunDuration;
    public readonly float StunDmgMultiplier;
    public readonly string IconLoc;


    public const int __ID__ = -165256153;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "name:" + Name + ","
        + "location:" + Location + ","
        + "hp:" + Hp + ","
        + "atk:" + Atk + ","
        + "def:" + Def + ","
        + "maxDaze:" + MaxDaze + ","
        + "stunDuration:" + StunDuration + ","
        + "stunDmgMultiplier:" + StunDmgMultiplier + ","
        + "iconLoc:" + IconLoc + ","
        + "}";
    }
}
}

