
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Newtonsoft.Json.Linq;



namespace cfg.main
{

public sealed partial class NPCConfig : Luban.BeanBase
{
    public NPCConfig(JToken _buf) 
    {
        JObject _obj = _buf as JObject;
        NpcId = (int)_obj.GetValue("npc_id");
        Name = (string)_obj.GetValue("name");
        DialogueConfigId = (int)_obj.GetValue("dialogue_config_id");
    }

    public static NPCConfig DeserializeNPCConfig(JToken _buf)
    {
        return new main.NPCConfig(_buf);
    }

    public readonly int NpcId;
    public readonly string Name;
    public readonly int DialogueConfigId;


    public const int __ID__ = -2038034578;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "npcId:" + NpcId + ","
        + "name:" + Name + ","
        + "dialogueConfigId:" + DialogueConfigId + ","
        + "}";
    }
}
}

