
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Newtonsoft.Json.Linq;



namespace cfg.main
{

public sealed partial class QuestChainConfig : Luban.BeanBase
{
    public QuestChainConfig(JToken _buf) 
    {
        JObject _obj = _buf as JObject;
        QuestChainConfigId = (int)_obj.GetValue("quest_chain_config_id");
        Name = (string)_obj.GetValue("name");
        { var __json0 = _obj.GetValue("rewords"); Rewords = new System.Collections.Generic.List<main.RewordConfig>((__json0 as JArray).Count); foreach(JToken __e0 in __json0) { main.RewordConfig __v0;  __v0 = main.RewordConfig.DeserializeRewordConfig(__e0);  Rewords.Add(__v0); }   }
        { var __json0 = _obj.GetValue("quests"); Quests = new System.Collections.Generic.List<main.QuestConfig>((__json0 as JArray).Count); foreach(JToken __e0 in __json0) { main.QuestConfig __v0;  __v0 = main.QuestConfig.DeserializeQuestConfig(__e0);  Quests.Add(__v0); }   }
    }

    public static QuestChainConfig DeserializeQuestChainConfig(JToken _buf)
    {
        return new main.QuestChainConfig(_buf);
    }

    /// <summary>
    /// 任务链id
    /// </summary>
    public readonly int QuestChainConfigId;
    /// <summary>
    /// 任务名称
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 奖励货币cid和数量
    /// </summary>
    public readonly System.Collections.Generic.List<main.RewordConfig> Rewords;
    /// <summary>
    /// 类型
    /// </summary>
    public readonly System.Collections.Generic.List<main.QuestConfig> Quests;


    public const int __ID__ = -765449514;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        foreach (var _e in Rewords) { _e?.ResolveRef(tables); }
        foreach (var _e in Quests) { _e?.ResolveRef(tables); }
    }

    public override string ToString()
    {
        return "{ "
        + "questChainConfigId:" + QuestChainConfigId + ","
        + "name:" + Name + ","
        + "rewords:" + Luban.StringUtil.CollectionToString(Rewords) + ","
        + "quests:" + Luban.StringUtil.CollectionToString(Quests) + ","
        + "}";
    }
}
}

