
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Newtonsoft.Json.Linq;



namespace cfg.main
{

public sealed partial class RoleConfig : Luban.BeanBase
{
    public RoleConfig(JToken _buf) 
    {
        JObject _obj = _buf as JObject;
        Id = (int)_obj.GetValue("id");
        Name = (string)_obj.GetValue("name");
        IconLoc = (string)_obj.GetValue("icon_loc");
        RoleSelectIconLoc = (string)_obj.GetValue("role_select_icon_loc");
        PrefabLoc = (string)_obj.GetValue("prefab_loc");
        SimPrefabLoc = (string)_obj.GetValue("sim_prefab_loc");
        IconRoleGeneralLoc = (string)_obj.GetValue("icon_role_general_loc");
    }

    public static RoleConfig DeserializeRoleConfig(JToken _buf)
    {
        return new main.RoleConfig(_buf);
    }

    /// <summary>
    /// 角色id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 名称
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 图标位置
    /// </summary>
    public readonly string IconLoc;
    public readonly string RoleSelectIconLoc;
    public readonly string PrefabLoc;
    public readonly string SimPrefabLoc;
    public readonly string IconRoleGeneralLoc;


    public const int __ID__ = 1850447565;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "name:" + Name + ","
        + "iconLoc:" + IconLoc + ","
        + "roleSelectIconLoc:" + RoleSelectIconLoc + ","
        + "prefabLoc:" + PrefabLoc + ","
        + "simPrefabLoc:" + SimPrefabLoc + ","
        + "iconRoleGeneralLoc:" + IconRoleGeneralLoc + ","
        + "}";
    }
}
}

