
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Newtonsoft.Json.Linq;
using Luban;



namespace cfg.main
{

public partial class TbAttrShowConfig
{
    private readonly System.Collections.Generic.Dictionary<main.EAttrType, main.AttrShowConfig> _dataMap;
    private readonly System.Collections.Generic.List<main.AttrShowConfig> _dataList;
    
    public TbAttrShowConfig(JArray _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<main.EAttrType, main.AttrShowConfig>();
        _dataList = new System.Collections.Generic.List<main.AttrShowConfig>();
        
        foreach(JObject _ele in _buf)
        {
            main.AttrShowConfig _v;
            _v = main.AttrShowConfig.DeserializeAttrShowConfig(_ele);
            _dataList.Add(_v);
            _dataMap.Add(_v.AttrType, _v);
         }
    }


    public System.Collections.Generic.Dictionary<main.EAttrType, main.AttrShowConfig> DataMap => _dataMap;
    public System.Collections.Generic.List<main.AttrShowConfig> DataList => _dataList;

    public main.AttrShowConfig GetOrDefault(main.EAttrType key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public main.AttrShowConfig Get(main.EAttrType key) => _dataMap[key];
    public main.AttrShowConfig this[main.EAttrType key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}
}

