
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Newtonsoft.Json.Linq;
using Luban;



namespace cfg.main
{

public partial class TbCharacterBaseAttrConfig
{
    private readonly System.Collections.Generic.Dictionary<int, main.CharacterBaseAttrConfig> _dataMap;
    private readonly System.Collections.Generic.List<main.CharacterBaseAttrConfig> _dataList;
    
    public TbCharacterBaseAttrConfig(JArray _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, main.CharacterBaseAttrConfig>();
        _dataList = new System.Collections.Generic.List<main.CharacterBaseAttrConfig>();
        
        foreach(JObject _ele in _buf)
        {
            main.CharacterBaseAttrConfig _v;
            _v = main.CharacterBaseAttrConfig.DeserializeCharacterBaseAttrConfig(_ele);
            _dataList.Add(_v);
            _dataMap.Add(_v.CharacterCid, _v);
         }
    }


    public System.Collections.Generic.Dictionary<int, main.CharacterBaseAttrConfig> DataMap => _dataMap;
    public System.Collections.Generic.List<main.CharacterBaseAttrConfig> DataList => _dataList;

    public main.CharacterBaseAttrConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public main.CharacterBaseAttrConfig Get(int key) => _dataMap[key];
    public main.CharacterBaseAttrConfig this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}
}

