
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Newtonsoft.Json.Linq;
using Luban;



namespace cfg.main
{

public partial class TbChHitNumericConfig
{
    private readonly System.Collections.Generic.Dictionary<int, main.ChHitNumericConfig> _dataMap;
    private readonly System.Collections.Generic.List<main.ChHitNumericConfig> _dataList;
    
    public TbChHitNumericConfig(JArray _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, main.ChHitNumericConfig>();
        _dataList = new System.Collections.Generic.List<main.ChHitNumericConfig>();
        
        foreach(JObject _ele in _buf)
        {
            main.ChHitNumericConfig _v;
            _v = main.ChHitNumericConfig.DeserializeChHitNumericConfig(_ele);
            _dataList.Add(_v);
            _dataMap.Add(_v.HitId, _v);
         }
    }


    public System.Collections.Generic.Dictionary<int, main.ChHitNumericConfig> DataMap => _dataMap;
    public System.Collections.Generic.List<main.ChHitNumericConfig> DataList => _dataList;

    public main.ChHitNumericConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public main.ChHitNumericConfig Get(int key) => _dataMap[key];
    public main.ChHitNumericConfig this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}
}

