
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Newtonsoft.Json.Linq;
using Luban;



namespace cfg.main
{

public partial class TbCurrencyItemConfig
{
    private readonly System.Collections.Generic.Dictionary<int, main.CurrencyItemConfig> _dataMap;
    private readonly System.Collections.Generic.List<main.CurrencyItemConfig> _dataList;
    
    public TbCurrencyItemConfig(JArray _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, main.CurrencyItemConfig>();
        _dataList = new System.Collections.Generic.List<main.CurrencyItemConfig>();
        
        foreach(JObject _ele in _buf)
        {
            main.CurrencyItemConfig _v;
            _v = main.CurrencyItemConfig.DeserializeCurrencyItemConfig(_ele);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
         }
    }


    public System.Collections.Generic.Dictionary<int, main.CurrencyItemConfig> DataMap => _dataMap;
    public System.Collections.Generic.List<main.CurrencyItemConfig> DataList => _dataList;

    public main.CurrencyItemConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public main.CurrencyItemConfig Get(int key) => _dataMap[key];
    public main.CurrencyItemConfig this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}
}

