
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Newtonsoft.Json.Linq;
using Luban;



namespace cfg.main
{

public partial class TbDiscUpgradeExpConfig
{
    private readonly System.Collections.Generic.Dictionary<int, main.DiscUpgradeExpConfig> _dataMap;
    private readonly System.Collections.Generic.List<main.DiscUpgradeExpConfig> _dataList;
    
    public TbDiscUpgradeExpConfig(JArray _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, main.DiscUpgradeExpConfig>();
        _dataList = new System.Collections.Generic.List<main.DiscUpgradeExpConfig>();
        
        foreach(JObject _ele in _buf)
        {
            main.DiscUpgradeExpConfig _v;
            _v = main.DiscUpgradeExpConfig.DeserializeDiscUpgradeExpConfig(_ele);
            _dataList.Add(_v);
            _dataMap.Add(_v.Level, _v);
         }
    }


    public System.Collections.Generic.Dictionary<int, main.DiscUpgradeExpConfig> DataMap => _dataMap;
    public System.Collections.Generic.List<main.DiscUpgradeExpConfig> DataList => _dataList;

    public main.DiscUpgradeExpConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public main.DiscUpgradeExpConfig Get(int key) => _dataMap[key];
    public main.DiscUpgradeExpConfig this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}
}

