
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Newtonsoft.Json.Linq;
using Luban;



namespace cfg.main
{

public partial class TbMonsterConfig
{
    private readonly System.Collections.Generic.Dictionary<int, main.MonsterConfig> _dataMap;
    private readonly System.Collections.Generic.List<main.MonsterConfig> _dataList;
    
    public TbMonsterConfig(JArray _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, main.MonsterConfig>();
        _dataList = new System.Collections.Generic.List<main.MonsterConfig>();
        
        foreach(JObject _ele in _buf)
        {
            main.MonsterConfig _v;
            _v = main.MonsterConfig.DeserializeMonsterConfig(_ele);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
         }
    }


    public System.Collections.Generic.Dictionary<int, main.MonsterConfig> DataMap => _dataMap;
    public System.Collections.Generic.List<main.MonsterConfig> DataList => _dataList;

    public main.MonsterConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public main.MonsterConfig Get(int key) => _dataMap[key];
    public main.MonsterConfig this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}
}

