
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Newtonsoft.Json.Linq;
using Luban;



namespace cfg.main
{

public partial class TbNPCConfig
{
    private readonly System.Collections.Generic.Dictionary<int, main.NPCConfig> _dataMap;
    private readonly System.Collections.Generic.List<main.NPCConfig> _dataList;
    
    public TbNPCConfig(JArray _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, main.NPCConfig>();
        _dataList = new System.Collections.Generic.List<main.NPCConfig>();
        
        foreach(JObject _ele in _buf)
        {
            main.NPCConfig _v;
            _v = main.NPCConfig.DeserializeNPCConfig(_ele);
            _dataList.Add(_v);
            _dataMap.Add(_v.NpcId, _v);
         }
    }


    public System.Collections.Generic.Dictionary<int, main.NPCConfig> DataMap => _dataMap;
    public System.Collections.Generic.List<main.NPCConfig> DataList => _dataList;

    public main.NPCConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public main.NPCConfig Get(int key) => _dataMap[key];
    public main.NPCConfig this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}
}

