
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Newtonsoft.Json.Linq;
using Luban;



namespace cfg.main
{

public partial class TbQuestChainConfig
{
    private readonly System.Collections.Generic.Dictionary<int, main.QuestChainConfig> _dataMap;
    private readonly System.Collections.Generic.List<main.QuestChainConfig> _dataList;
    
    public TbQuestChainConfig(JArray _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, main.QuestChainConfig>();
        _dataList = new System.Collections.Generic.List<main.QuestChainConfig>();
        
        foreach(JObject _ele in _buf)
        {
            main.QuestChainConfig _v;
            _v = main.QuestChainConfig.DeserializeQuestChainConfig(_ele);
            _dataList.Add(_v);
            _dataMap.Add(_v.QuestChainConfigId, _v);
         }
    }


    public System.Collections.Generic.Dictionary<int, main.QuestChainConfig> DataMap => _dataMap;
    public System.Collections.Generic.List<main.QuestChainConfig> DataList => _dataList;

    public main.QuestChainConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public main.QuestChainConfig Get(int key) => _dataMap[key];
    public main.QuestChainConfig this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}
}

