
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Newtonsoft.Json.Linq;



namespace cfg.main
{

public sealed partial class WeaponConfig : Luban.BeanBase
{
    public WeaponConfig(JToken _buf) 
    {
        JObject _obj = _buf as JObject;
        Id = (int)_obj.GetValue("id");
        Name = (string)_obj.GetValue("name");
        Rank = (string)_obj.GetValue("rank");
        IconLoc = (string)_obj.GetValue("icon_loc");
        MaxLevelBaseAttrType = (main.EAttrType)(int)_obj.GetValue("max_level_base_attr_type");
        MaxLevelBaseAttrValue = (float)_obj.GetValue("max_level_base_attr_value");
        MaxLevelAdvancedAttrType = (main.EAttrType)(int)_obj.GetValue("max_level_advanced_attr_type");
        MaxLevelAdvancedAttrValue = (float)_obj.GetValue("max_level_advanced_attr_value");
        PassiveAbilityName = (string)_obj.GetValue("passive_ability_name");
        PassiveDesc = (string)_obj.GetValue("passive_desc");
        Desc = (string)_obj.GetValue("desc");
    }

    public static WeaponConfig DeserializeWeaponConfig(JToken _buf)
    {
        return new main.WeaponConfig(_buf);
    }

    public readonly int Id;
    /// <summary>
    /// 名称
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 级别
    /// </summary>
    public readonly string Rank;
    /// <summary>
    /// 图标路径
    /// </summary>
    public readonly string IconLoc;
    /// <summary>
    /// 最大等级基础属性类型
    /// </summary>
    public readonly main.EAttrType MaxLevelBaseAttrType;
    /// <summary>
    /// 最大等级主属性值
    /// </summary>
    public readonly float MaxLevelBaseAttrValue;
    /// <summary>
    /// 最大等级进阶属性名
    /// </summary>
    public readonly main.EAttrType MaxLevelAdvancedAttrType;
    /// <summary>
    /// 最大等级进阶属性值
    /// </summary>
    public readonly float MaxLevelAdvancedAttrValue;
    /// <summary>
    /// 被动效果名
    /// </summary>
    public readonly string PassiveAbilityName;
    /// <summary>
    /// 被动描述
    /// </summary>
    public readonly string PassiveDesc;
    /// <summary>
    /// 描述
    /// </summary>
    public readonly string Desc;


    public const int __ID__ = -1677624653;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "name:" + Name + ","
        + "rank:" + Rank + ","
        + "iconLoc:" + IconLoc + ","
        + "maxLevelBaseAttrType:" + MaxLevelBaseAttrType + ","
        + "maxLevelBaseAttrValue:" + MaxLevelBaseAttrValue + ","
        + "maxLevelAdvancedAttrType:" + MaxLevelAdvancedAttrType + ","
        + "maxLevelAdvancedAttrValue:" + MaxLevelAdvancedAttrValue + ","
        + "passiveAbilityName:" + PassiveAbilityName + ","
        + "passiveDesc:" + PassiveDesc + ","
        + "desc:" + Desc + ","
        + "}";
    }
}
}

