// 本文件为生成的代码，所有修改都会丢失
using System;
using System.Collections.Generic;
public static class MsgMetaInitializer
{
    public static MsgMeta Init(this MsgMeta meta)
    {
        meta.items = new[]
        {
            new MsgMetaItem(MsgCmdId.Result, Result.Parser, false),
            new MsgMetaItem(MsgCmdId.Ping, Ping.Parser, false),
            new MsgMetaItem(MsgCmdId.Pong, Pong.Parser, true),
            new MsgMetaItem(MsgCmdId.NPlayer, NPlayer.Parser, false),
            new MsgMetaItem(MsgCmdId.NSocialPlayer, NSocialPlayer.Parser, false),
            new MsgMetaItem(MsgCmdId.NMaterialItem, NMaterialItem.Parser, false),
            new MsgMetaItem(MsgCmdId.NCurrencyItem, NCurrencyItem.Parser, false),
            new MsgMetaItem(MsgCmdId.NWeaponItem, NWeaponItem.Parser, false),
            new MsgMetaItem(MsgCmdId.NDiscItem, NDiscItem.Parser, false),
            new MsgMetaItem(MsgCmdId.NVector3, NVector3.Parser, false),
            new MsgMetaItem(MsgCmdId.NMovement, NMovement.Parser, false),
            new MsgMetaItem(MsgCmdId.NWeaponAttr, NWeaponAttr.Parser, false),
            new MsgMetaItem(MsgCmdId.NDiscAttr, NDiscAttr.Parser, false),
            new MsgMetaItem(MsgCmdId.MsgGachaWeapon, MsgGachaWeapon.Parser, false),
            new MsgMetaItem(MsgCmdId.MsgGachaDisc, MsgGachaDisc.Parser, false),
            new MsgMetaItem(MsgCmdId.ReqRegister, ReqRegister.Parser, false),
            new MsgMetaItem(MsgCmdId.RspRegister, RspRegister.Parser, true),
            new MsgMetaItem(MsgCmdId.ReqLogin, ReqLogin.Parser, false),
            new MsgMetaItem(MsgCmdId.RspLogin, RspLogin.Parser, true),
            new MsgMetaItem(MsgCmdId.ReqGetPlayerData, ReqGetPlayerData.Parser, false),
            new MsgMetaItem(MsgCmdId.RspGetPlayerData, RspGetPlayerData.Parser, true),
            new MsgMetaItem(MsgCmdId.NSyncRole, NSyncRole.Parser, false),
            new MsgMetaItem(MsgCmdId.NSyncPlayer, NSyncPlayer.Parser, false),
            new MsgMetaItem(MsgCmdId.MsgEnterRoom, MsgEnterRoom.Parser, false),
            new MsgMetaItem(MsgCmdId.MsgUpdateFromAutonomous, MsgUpdateFromAutonomous.Parser, false),
            new MsgMetaItem(MsgCmdId.NotifyUpdateFromAuthority, NotifyUpdateFromAuthority.Parser, false),
            new MsgMetaItem(MsgCmdId.NotifyRemoveSimulatedPlayers, NotifyRemoveSimulatedPlayers.Parser, false),
            new MsgMetaItem(MsgCmdId.MsgRolePlayAction, MsgRolePlayAction.Parser, false),
            new MsgMetaItem(MsgCmdId.NotifyOtherRolePlayAction, NotifyOtherRolePlayAction.Parser, false),
            new MsgMetaItem(MsgCmdId.MsgSwitchRole, MsgSwitchRole.Parser, false),
            new MsgMetaItem(MsgCmdId.ReqGetExchangeItems, ReqGetExchangeItems.Parser, false),
            new MsgMetaItem(MsgCmdId.RspGetExchangeItems, RspGetExchangeItems.Parser, true),
            new MsgMetaItem(MsgCmdId.NExchangeItem, NExchangeItem.Parser, false),
            new MsgMetaItem(MsgCmdId.ReqExchange, ReqExchange.Parser, false),
            new MsgMetaItem(MsgCmdId.RspExchange, RspExchange.Parser, true),
            new MsgMetaItem(MsgCmdId.ReqSearchPlayer, ReqSearchPlayer.Parser, false),
            new MsgMetaItem(MsgCmdId.RspSearchPlayer, RspSearchPlayer.Parser, true),
            new MsgMetaItem(MsgCmdId.ReqSendAddFriend, ReqSendAddFriend.Parser, false),
            new MsgMetaItem(MsgCmdId.RspSendAddFriend, RspSendAddFriend.Parser, true),
            new MsgMetaItem(MsgCmdId.NotifyFriendRequestsAdd, NotifyFriendRequestsAdd.Parser, false),
            new MsgMetaItem(MsgCmdId.NotifyFriendRequestsRemove, NotifyFriendRequestsRemove.Parser, false),
            new MsgMetaItem(MsgCmdId.NotifyFriendsAdd, NotifyFriendsAdd.Parser, false),
            new MsgMetaItem(MsgCmdId.NotifyFriendsRemove, NotifyFriendsRemove.Parser, false),
            new MsgMetaItem(MsgCmdId.ReqAcceptAddFriend, ReqAcceptAddFriend.Parser, false),
            new MsgMetaItem(MsgCmdId.RspAcceptAddFriend, RspAcceptAddFriend.Parser, true),
            new MsgMetaItem(MsgCmdId.ReqRefuseAddFriend, ReqRefuseAddFriend.Parser, false),
            new MsgMetaItem(MsgCmdId.RspRefuseAddFriend, RspRefuseAddFriend.Parser, true),
            new MsgMetaItem(MsgCmdId.ReqRemoveFriend, ReqRemoveFriend.Parser, false),
            new MsgMetaItem(MsgCmdId.RspRemoveFriend, RspRemoveFriend.Parser, true),
            new MsgMetaItem(MsgCmdId.ReqModifySignature, ReqModifySignature.Parser, false),
            new MsgMetaItem(MsgCmdId.RspModifySignature, RspModifySignature.Parser, true),
            new MsgMetaItem(MsgCmdId.ReqModifyPassword, ReqModifyPassword.Parser, false),
            new MsgMetaItem(MsgCmdId.RspModifyPassword, RspModifyPassword.Parser, true),
            new MsgMetaItem(MsgCmdId.ReqModifyAvatar, ReqModifyAvatar.Parser, false),
            new MsgMetaItem(MsgCmdId.RspModifyAvatar, RspModifyAvatar.Parser, true),
            new MsgMetaItem(MsgCmdId.NChatMsg, NChatMsg.Parser, false),
            new MsgMetaItem(MsgCmdId.ReqSendChatMsg, ReqSendChatMsg.Parser, false),
            new MsgMetaItem(MsgCmdId.RspSendChatMsg, RspSendChatMsg.Parser, true),
            new MsgMetaItem(MsgCmdId.NotifyReceiveChatMsg, NotifyReceiveChatMsg.Parser, false),
            new MsgMetaItem(MsgCmdId.NRole, NRole.Parser, false),
            new MsgMetaItem(MsgCmdId.ReqRoleRemoveDisc, ReqRoleRemoveDisc.Parser, false),
            new MsgMetaItem(MsgCmdId.RspRoleRemoveDisc, RspRoleRemoveDisc.Parser, true),
            new MsgMetaItem(MsgCmdId.ReqRoleEquipDisc, ReqRoleEquipDisc.Parser, false),
            new MsgMetaItem(MsgCmdId.RspRoleEquipDisc, RspRoleEquipDisc.Parser, true),
            new MsgMetaItem(MsgCmdId.ReqRoleRemoveWeapon, ReqRoleRemoveWeapon.Parser, false),
            new MsgMetaItem(MsgCmdId.RspRoleRemoveWeapon, RspRoleRemoveWeapon.Parser, true),
            new MsgMetaItem(MsgCmdId.ReqRoleEquipWeapon, ReqRoleEquipWeapon.Parser, false),
            new MsgMetaItem(MsgCmdId.RspRoleEquipWeapon, RspRoleEquipWeapon.Parser, true),
            new MsgMetaItem(MsgCmdId.NotifyMonsterDie, NotifyMonsterDie.Parser, false),
            new MsgMetaItem(MsgCmdId.MsgMonsterTakeDamage, MsgMonsterTakeDamage.Parser, false),
            new MsgMetaItem(MsgCmdId.NotifyMonsterTakeDamage, NotifyMonsterTakeDamage.Parser, false),
            new MsgMetaItem(MsgCmdId.NQuaternion, NQuaternion.Parser, false),
            new MsgMetaItem(MsgCmdId.NSyncMonster, NSyncMonster.Parser, false),
            new MsgMetaItem(MsgCmdId.NotifyUpdateMonster, NotifyUpdateMonster.Parser, false),
            new MsgMetaItem(MsgCmdId.NotifyMonsterPlayAction, NotifyMonsterPlayAction.Parser, false),
            new MsgMetaItem(MsgCmdId.ReqStartQuest, ReqStartQuest.Parser, false),
            new MsgMetaItem(MsgCmdId.RspStartQuest, RspStartQuest.Parser, true),
            new MsgMetaItem(MsgCmdId.ReqUpgradeDisc, ReqUpgradeDisc.Parser, false),
            new MsgMetaItem(MsgCmdId.RspUpgradeDisc, RspUpgradeDisc.Parser, true),
            new MsgMetaItem(MsgCmdId.MsgGatherMaterial, MsgGatherMaterial.Parser, false),
            new MsgMetaItem(MsgCmdId.MsgCompleteQuestChain, MsgCompleteQuestChain.Parser, false),
            new MsgMetaItem(MsgCmdId.NotifyObtainItems, NotifyObtainItems.Parser, false),
            new MsgMetaItem(MsgCmdId.NotifyMonsterAttackRole, NotifyMonsterAttackRole.Parser, false),
            new MsgMetaItem(MsgCmdId.MsgRoleSetParry, MsgRoleSetParry.Parser, false),
            new MsgMetaItem(MsgCmdId.MsgRoleSetDodge, MsgRoleSetDodge.Parser, false),
            new MsgMetaItem(MsgCmdId.NotifyMonsterPath, NotifyMonsterPath.Parser, false),
        };
    
        meta.cmdIdToItem = new Dictionary<uint, MsgMetaItem>
        {
            {MsgCmdId.Result, meta.items[0]},
            {MsgCmdId.Ping, meta.items[1]},
            {MsgCmdId.Pong, meta.items[2]},
            {MsgCmdId.NPlayer, meta.items[3]},
            {MsgCmdId.NSocialPlayer, meta.items[4]},
            {MsgCmdId.NMaterialItem, meta.items[5]},
            {MsgCmdId.NCurrencyItem, meta.items[6]},
            {MsgCmdId.NWeaponItem, meta.items[7]},
            {MsgCmdId.NDiscItem, meta.items[8]},
            {MsgCmdId.NVector3, meta.items[9]},
            {MsgCmdId.NMovement, meta.items[10]},
            {MsgCmdId.NWeaponAttr, meta.items[11]},
            {MsgCmdId.NDiscAttr, meta.items[12]},
            {MsgCmdId.MsgGachaWeapon, meta.items[13]},
            {MsgCmdId.MsgGachaDisc, meta.items[14]},
            {MsgCmdId.ReqRegister, meta.items[15]},
            {MsgCmdId.RspRegister, meta.items[16]},
            {MsgCmdId.ReqLogin, meta.items[17]},
            {MsgCmdId.RspLogin, meta.items[18]},
            {MsgCmdId.ReqGetPlayerData, meta.items[19]},
            {MsgCmdId.RspGetPlayerData, meta.items[20]},
            {MsgCmdId.NSyncRole, meta.items[21]},
            {MsgCmdId.NSyncPlayer, meta.items[22]},
            {MsgCmdId.MsgEnterRoom, meta.items[23]},
            {MsgCmdId.MsgUpdateFromAutonomous, meta.items[24]},
            {MsgCmdId.NotifyUpdateFromAuthority, meta.items[25]},
            {MsgCmdId.NotifyRemoveSimulatedPlayers, meta.items[26]},
            {MsgCmdId.MsgRolePlayAction, meta.items[27]},
            {MsgCmdId.NotifyOtherRolePlayAction, meta.items[28]},
            {MsgCmdId.MsgSwitchRole, meta.items[29]},
            {MsgCmdId.ReqGetExchangeItems, meta.items[30]},
            {MsgCmdId.RspGetExchangeItems, meta.items[31]},
            {MsgCmdId.NExchangeItem, meta.items[32]},
            {MsgCmdId.ReqExchange, meta.items[33]},
            {MsgCmdId.RspExchange, meta.items[34]},
            {MsgCmdId.ReqSearchPlayer, meta.items[35]},
            {MsgCmdId.RspSearchPlayer, meta.items[36]},
            {MsgCmdId.ReqSendAddFriend, meta.items[37]},
            {MsgCmdId.RspSendAddFriend, meta.items[38]},
            {MsgCmdId.NotifyFriendRequestsAdd, meta.items[39]},
            {MsgCmdId.NotifyFriendRequestsRemove, meta.items[40]},
            {MsgCmdId.NotifyFriendsAdd, meta.items[41]},
            {MsgCmdId.NotifyFriendsRemove, meta.items[42]},
            {MsgCmdId.ReqAcceptAddFriend, meta.items[43]},
            {MsgCmdId.RspAcceptAddFriend, meta.items[44]},
            {MsgCmdId.ReqRefuseAddFriend, meta.items[45]},
            {MsgCmdId.RspRefuseAddFriend, meta.items[46]},
            {MsgCmdId.ReqRemoveFriend, meta.items[47]},
            {MsgCmdId.RspRemoveFriend, meta.items[48]},
            {MsgCmdId.ReqModifySignature, meta.items[49]},
            {MsgCmdId.RspModifySignature, meta.items[50]},
            {MsgCmdId.ReqModifyPassword, meta.items[51]},
            {MsgCmdId.RspModifyPassword, meta.items[52]},
            {MsgCmdId.ReqModifyAvatar, meta.items[53]},
            {MsgCmdId.RspModifyAvatar, meta.items[54]},
            {MsgCmdId.NChatMsg, meta.items[55]},
            {MsgCmdId.ReqSendChatMsg, meta.items[56]},
            {MsgCmdId.RspSendChatMsg, meta.items[57]},
            {MsgCmdId.NotifyReceiveChatMsg, meta.items[58]},
            {MsgCmdId.NRole, meta.items[59]},
            {MsgCmdId.ReqRoleRemoveDisc, meta.items[60]},
            {MsgCmdId.RspRoleRemoveDisc, meta.items[61]},
            {MsgCmdId.ReqRoleEquipDisc, meta.items[62]},
            {MsgCmdId.RspRoleEquipDisc, meta.items[63]},
            {MsgCmdId.ReqRoleRemoveWeapon, meta.items[64]},
            {MsgCmdId.RspRoleRemoveWeapon, meta.items[65]},
            {MsgCmdId.ReqRoleEquipWeapon, meta.items[66]},
            {MsgCmdId.RspRoleEquipWeapon, meta.items[67]},
            {MsgCmdId.NotifyMonsterDie, meta.items[68]},
            {MsgCmdId.MsgMonsterTakeDamage, meta.items[69]},
            {MsgCmdId.NotifyMonsterTakeDamage, meta.items[70]},
            {MsgCmdId.NQuaternion, meta.items[71]},
            {MsgCmdId.NSyncMonster, meta.items[72]},
            {MsgCmdId.NotifyUpdateMonster, meta.items[73]},
            {MsgCmdId.NotifyMonsterPlayAction, meta.items[74]},
            {MsgCmdId.ReqStartQuest, meta.items[75]},
            {MsgCmdId.RspStartQuest, meta.items[76]},
            {MsgCmdId.ReqUpgradeDisc, meta.items[77]},
            {MsgCmdId.RspUpgradeDisc, meta.items[78]},
            {MsgCmdId.MsgGatherMaterial, meta.items[79]},
            {MsgCmdId.MsgCompleteQuestChain, meta.items[80]},
            {MsgCmdId.NotifyObtainItems, meta.items[81]},
            {MsgCmdId.NotifyMonsterAttackRole, meta.items[82]},
            {MsgCmdId.MsgRoleSetParry, meta.items[83]},
            {MsgCmdId.MsgRoleSetDodge, meta.items[84]},
            {MsgCmdId.NotifyMonsterPath, meta.items[85]},
        };

        meta.typeToItem = new Dictionary<Type, MsgMetaItem>
        {
            {typeof(Result), meta.items[0]},
            {typeof(Ping), meta.items[1]},
            {typeof(Pong), meta.items[2]},
            {typeof(NPlayer), meta.items[3]},
            {typeof(NSocialPlayer), meta.items[4]},
            {typeof(NMaterialItem), meta.items[5]},
            {typeof(NCurrencyItem), meta.items[6]},
            {typeof(NWeaponItem), meta.items[7]},
            {typeof(NDiscItem), meta.items[8]},
            {typeof(NVector3), meta.items[9]},
            {typeof(NMovement), meta.items[10]},
            {typeof(NWeaponAttr), meta.items[11]},
            {typeof(NDiscAttr), meta.items[12]},
            {typeof(MsgGachaWeapon), meta.items[13]},
            {typeof(MsgGachaDisc), meta.items[14]},
            {typeof(ReqRegister), meta.items[15]},
            {typeof(RspRegister), meta.items[16]},
            {typeof(ReqLogin), meta.items[17]},
            {typeof(RspLogin), meta.items[18]},
            {typeof(ReqGetPlayerData), meta.items[19]},
            {typeof(RspGetPlayerData), meta.items[20]},
            {typeof(NSyncRole), meta.items[21]},
            {typeof(NSyncPlayer), meta.items[22]},
            {typeof(MsgEnterRoom), meta.items[23]},
            {typeof(MsgUpdateFromAutonomous), meta.items[24]},
            {typeof(NotifyUpdateFromAuthority), meta.items[25]},
            {typeof(NotifyRemoveSimulatedPlayers), meta.items[26]},
            {typeof(MsgRolePlayAction), meta.items[27]},
            {typeof(NotifyOtherRolePlayAction), meta.items[28]},
            {typeof(MsgSwitchRole), meta.items[29]},
            {typeof(ReqGetExchangeItems), meta.items[30]},
            {typeof(RspGetExchangeItems), meta.items[31]},
            {typeof(NExchangeItem), meta.items[32]},
            {typeof(ReqExchange), meta.items[33]},
            {typeof(RspExchange), meta.items[34]},
            {typeof(ReqSearchPlayer), meta.items[35]},
            {typeof(RspSearchPlayer), meta.items[36]},
            {typeof(ReqSendAddFriend), meta.items[37]},
            {typeof(RspSendAddFriend), meta.items[38]},
            {typeof(NotifyFriendRequestsAdd), meta.items[39]},
            {typeof(NotifyFriendRequestsRemove), meta.items[40]},
            {typeof(NotifyFriendsAdd), meta.items[41]},
            {typeof(NotifyFriendsRemove), meta.items[42]},
            {typeof(ReqAcceptAddFriend), meta.items[43]},
            {typeof(RspAcceptAddFriend), meta.items[44]},
            {typeof(ReqRefuseAddFriend), meta.items[45]},
            {typeof(RspRefuseAddFriend), meta.items[46]},
            {typeof(ReqRemoveFriend), meta.items[47]},
            {typeof(RspRemoveFriend), meta.items[48]},
            {typeof(ReqModifySignature), meta.items[49]},
            {typeof(RspModifySignature), meta.items[50]},
            {typeof(ReqModifyPassword), meta.items[51]},
            {typeof(RspModifyPassword), meta.items[52]},
            {typeof(ReqModifyAvatar), meta.items[53]},
            {typeof(RspModifyAvatar), meta.items[54]},
            {typeof(NChatMsg), meta.items[55]},
            {typeof(ReqSendChatMsg), meta.items[56]},
            {typeof(RspSendChatMsg), meta.items[57]},
            {typeof(NotifyReceiveChatMsg), meta.items[58]},
            {typeof(NRole), meta.items[59]},
            {typeof(ReqRoleRemoveDisc), meta.items[60]},
            {typeof(RspRoleRemoveDisc), meta.items[61]},
            {typeof(ReqRoleEquipDisc), meta.items[62]},
            {typeof(RspRoleEquipDisc), meta.items[63]},
            {typeof(ReqRoleRemoveWeapon), meta.items[64]},
            {typeof(RspRoleRemoveWeapon), meta.items[65]},
            {typeof(ReqRoleEquipWeapon), meta.items[66]},
            {typeof(RspRoleEquipWeapon), meta.items[67]},
            {typeof(NotifyMonsterDie), meta.items[68]},
            {typeof(MsgMonsterTakeDamage), meta.items[69]},
            {typeof(NotifyMonsterTakeDamage), meta.items[70]},
            {typeof(NQuaternion), meta.items[71]},
            {typeof(NSyncMonster), meta.items[72]},
            {typeof(NotifyUpdateMonster), meta.items[73]},
            {typeof(NotifyMonsterPlayAction), meta.items[74]},
            {typeof(ReqStartQuest), meta.items[75]},
            {typeof(RspStartQuest), meta.items[76]},
            {typeof(ReqUpgradeDisc), meta.items[77]},
            {typeof(RspUpgradeDisc), meta.items[78]},
            {typeof(MsgGatherMaterial), meta.items[79]},
            {typeof(MsgCompleteQuestChain), meta.items[80]},
            {typeof(NotifyObtainItems), meta.items[81]},
            {typeof(NotifyMonsterAttackRole), meta.items[82]},
            {typeof(MsgRoleSetParry), meta.items[83]},
            {typeof(MsgRoleSetDodge), meta.items[84]},
            {typeof(NotifyMonsterPath), meta.items[85]},
        };
        
        return meta;
    }
}