
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Newtonsoft.Json.Linq;



namespace cfg.main
{

public sealed partial class CharacterBaseAttrConfig : Luban.BeanBase
{
    public CharacterBaseAttrConfig(JToken _buf) 
    {
        JObject _obj = _buf as JObject;
        CharacterCid = (int)_obj.GetValue("character_cid");
        { var __json0 = _obj.GetValue("ch_base_attrs"); ChBaseAttrs = new System.Collections.Generic.List<main.ChBaseAttrConfig>((__json0 as JArray).Count); foreach(JToken __e0 in __json0) { main.ChBaseAttrConfig __v0;  __v0 = main.ChBaseAttrConfig.DeserializeChBaseAttrConfig(__e0);  ChBaseAttrs.Add(__v0); }   }
    }

    public static CharacterBaseAttrConfig DeserializeCharacterBaseAttrConfig(JToken _buf)
    {
        return new main.CharacterBaseAttrConfig(_buf);
    }

    public readonly int CharacterCid;
    public readonly System.Collections.Generic.List<main.ChBaseAttrConfig> ChBaseAttrs;


    public const int __ID__ = -1289544584;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        foreach (var _e in ChBaseAttrs) { _e?.ResolveRef(tables); }
    }

    public override string ToString()
    {
        return "{ "
        + "characterCid:" + CharacterCid + ","
        + "chBaseAttrs:" + Luban.StringUtil.CollectionToString(ChBaseAttrs) + ","
        + "}";
    }
}
}

