
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Newtonsoft.Json.Linq;



namespace cfg.main
{

public sealed partial class DialogueOptionsConfig : Luban.BeanBase
{
    public DialogueOptionsConfig(JToken _buf) 
    {
        JObject _obj = _buf as JObject;
        SubCid = (int)_obj.GetValue("sub_cid");
        { var __json0 = _obj.GetValue("options"); Options = new System.Collections.Generic.List<main.DialogueOptionConfig>((__json0 as JArray).Count); foreach(JToken __e0 in __json0) { main.DialogueOptionConfig __v0;  __v0 = main.DialogueOptionConfig.DeserializeDialogueOptionConfig(__e0);  Options.Add(__v0); }   }
    }

    public static DialogueOptionsConfig DeserializeDialogueOptionsConfig(JToken _buf)
    {
        return new main.DialogueOptionsConfig(_buf);
    }

    public readonly int SubCid;
    public readonly System.Collections.Generic.List<main.DialogueOptionConfig> Options;


    public const int __ID__ = 846395891;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        foreach (var _e in Options) { _e?.ResolveRef(tables); }
    }

    public override string ToString()
    {
        return "{ "
        + "subCid:" + SubCid + ","
        + "options:" + Luban.StringUtil.CollectionToString(Options) + ","
        + "}";
    }
}
}

