
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Newtonsoft.Json.Linq;



namespace cfg.main
{

public sealed partial class DialogueQuestConfig : main.QuestConfig
{
    public DialogueQuestConfig(JToken _buf)  : base(_buf) 
    {
        JObject _obj = _buf as JObject;
        DialogueCid = (int)_obj.GetValue("dialogue_cid");
    }

    public static DialogueQuestConfig DeserializeDialogueQuestConfig(JToken _buf)
    {
        return new main.DialogueQuestConfig(_buf);
    }

    public readonly int DialogueCid;


    public const int __ID__ = -679622153;
    public override int GetTypeId() => __ID__;

    public override void ResolveRef(Tables tables)
    {
        base.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "questCid:" + QuestCid + ","
        + "nextQuestCid:" + NextQuestCid + ","
        + "name:" + Name + ","
        + "desc:" + Desc + ","
        + "npcOverrides:" + Luban.StringUtil.CollectionToString(NpcOverrides) + ","
        + "completeGetQuestChainCid:" + CompleteGetQuestChainCid + ","
        + "trunkNpcCids:" + Luban.StringUtil.CollectionToString(TrunkNpcCids) + ","
        + "dialogueCid:" + DialogueCid + ","
        + "}";
    }
}
}

