
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Newtonsoft.Json.Linq;



namespace cfg.main
{

public sealed partial class DiscConfig : Luban.BeanBase
{
    public DiscConfig(JToken _buf) 
    {
        JObject _obj = _buf as JObject;
        Id = (int)_obj.GetValue("id");
        Name = (string)_obj.GetValue("name");
        Rank = (string)_obj.GetValue("rank");
        IconLoc = (string)_obj.GetValue("icon_loc");
        EquipmentIconLoc = (string)_obj.GetValue("equipment_icon_loc");
        SetAbility2Name = (string)_obj.GetValue("set_ability_2_name");
        SetAbility4Name = (string)_obj.GetValue("set_ability_4_name");
        SetAbility2Desc = (string)_obj.GetValue("set_ability_2_desc");
        SetAbility4Desc = (string)_obj.GetValue("set_ability_4_desc");
        Desc = (string)_obj.GetValue("desc");
    }

    public static DiscConfig DeserializeDiscConfig(JToken _buf)
    {
        return new main.DiscConfig(_buf);
    }

    public readonly int Id;
    /// <summary>
    /// 名称
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 级别
    /// </summary>
    public readonly string Rank;
    /// <summary>
    /// 图标路径
    /// </summary>
    public readonly string IconLoc;
    /// <summary>
    /// 装备页图标路径
    /// </summary>
    public readonly string EquipmentIconLoc;
    /// <summary>
    /// 2件套效果名
    /// </summary>
    public readonly string SetAbility2Name;
    /// <summary>
    /// 4件套效果名
    /// </summary>
    public readonly string SetAbility4Name;
    /// <summary>
    /// 2件套描述
    /// </summary>
    public readonly string SetAbility2Desc;
    /// <summary>
    /// 4件套描述
    /// </summary>
    public readonly string SetAbility4Desc;
    /// <summary>
    /// 描述
    /// </summary>
    public readonly string Desc;


    public const int __ID__ = 101224620;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "name:" + Name + ","
        + "rank:" + Rank + ","
        + "iconLoc:" + IconLoc + ","
        + "equipmentIconLoc:" + EquipmentIconLoc + ","
        + "setAbility2Name:" + SetAbility2Name + ","
        + "setAbility4Name:" + SetAbility4Name + ","
        + "setAbility2Desc:" + SetAbility2Desc + ","
        + "setAbility4Desc:" + SetAbility4Desc + ","
        + "desc:" + Desc + ","
        + "}";
    }
}
}

