
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg.main
{ 
    public enum EAttrType
    {
        /// <summary>
        /// 攻击力
        /// </summary>
        Atk = 100,
        /// <summary>
        /// 基础攻击力
        /// </summary>
        AtkBase = 101,
        /// <summary>
        /// 百分比攻击力
        /// </summary>
        AtkPct = 102,
        /// <summary>
        /// 固定攻击力
        /// </summary>
        AtkFixed = 103,
        /// <summary>
        /// 防御力
        /// </summary>
        Def = 200,
        /// <summary>
        /// 基础防御力
        /// </summary>
        DefBase = 201,
        /// <summary>
        /// 百分比防御力
        /// </summary>
        DefPct = 202,
        /// <summary>
        /// 固定防御力
        /// </summary>
        DefFixed = 203,
        /// <summary>
        /// 生命值
        /// </summary>
        Hp = 300,
        /// <summary>
        /// 基础生命值
        /// </summary>
        HpBase = 301,
        /// <summary>
        /// 百分比生命值
        /// </summary>
        HpPct = 302,
        /// <summary>
        /// 固定生命值
        /// </summary>
        HpFixed = 303,
        /// <summary>
        /// 冲击力
        /// </summary>
        Impact = 400,
        /// <summary>
        /// 基础冲击力
        /// </summary>
        ImpactBase = 401,
        /// <summary>
        /// 百分比冲击力
        /// </summary>
        ImpactPct = 402,
        /// <summary>
        /// 固定冲击力
        /// </summary>
        ImpactFixed = 403,
        /// <summary>
        /// 异常掌控
        /// </summary>
        AnomalyMastery = 500,
        /// <summary>
        /// 基础异常掌控
        /// </summary>
        AnomalyMasteryBase = 501,
        /// <summary>
        /// 百分比异常掌控
        /// </summary>
        AnomalyMasteryPct = 502,
        /// <summary>
        /// 固定异常掌控
        /// </summary>
        AnomalyMasteryFixed = 503,
        /// <summary>
        /// 异常精通
        /// </summary>
        AnomalyProficiency = 600,
        /// <summary>
        /// 基础异常精通
        /// </summary>
        AnomalyProficiencyBase = 601,
        /// <summary>
        /// 百分比异常精通
        /// </summary>
        AnomalyProficiencyPct = 602,
        /// <summary>
        /// 固定异常精通
        /// </summary>
        AnomalyProficiencyFixed = 603,
        /// <summary>
        /// 能量自动回复
        /// </summary>
        EnergyRegen = 700,
        /// <summary>
        /// 基础能量自动回复
        /// </summary>
        EnergyRegenBase = 701,
        /// <summary>
        /// 百分比能量自动回复
        /// </summary>
        EnergyRegenPct = 702,
        /// <summary>
        /// 固定能量自动回复
        /// </summary>
        EnergyRegenFixed = 703,
        /// <summary>
        /// 暴击率
        /// </summary>
        CritRate = 800,
        /// <summary>
        /// 暴击伤害
        /// </summary>
        CritDmg = 900,
        /// <summary>
        /// 穿透率
        /// </summary>
        PenRatio = 1000,
        /// <summary>
        /// 穿透值
        /// </summary>
        Pen = 1100,
        /// <summary>
        /// 增伤
        /// </summary>
        ZengShang = 1200,
        /// <summary>
        /// 能量获得效率
        /// </summary>
        EnergyEffi = 1300,
        /// <summary>
        /// 造成失衡值提升
        /// </summary>
        DazeUp = 1400,
        /// <summary>
        /// 当前生命值
        /// </summary>
        CurrHp = 1500,
        /// <summary>
        /// 当前能量值
        /// </summary>
        CurrEnergy = 1600,
        /// <summary>
        /// 无敌
        /// </summary>
        Invincible = 1700,
        /// <summary>
        /// 当前失衡值
        /// </summary>
        CurrDaze = 1800,
        /// <summary>
        /// 最大失衡值
        /// </summary>
        MaxDaze = 1900,
        /// <summary>
        /// 失衡时间
        /// </summary>
        StunDuration = 2000,
        /// <summary>
        /// 失衡易伤倍率
        /// </summary>
        StunDmgMultiplier = 2100,
    }

} 

