
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg.main
{ 
    public enum EffectDurationPolicyConfig
    {
        /// <summary>
        /// 瞬间
        /// </summary>
        Instant = 0,
        /// <summary>
        /// 永久
        /// </summary>
        Infinite = 1,
        /// <summary>
        /// 持续
        /// </summary>
        HasDuration = 2,
    }

} 

