
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Newtonsoft.Json.Linq;



namespace cfg.main
{

public sealed partial class ExchangeConfig : Luban.BeanBase
{
    public ExchangeConfig(JToken _buf) 
    {
        JObject _obj = _buf as JObject;
        ExchangeId = (int)_obj.GetValue("exchange_id");
        FromConfigId = (int)_obj.GetValue("from_config_id");
        FromCount = (int)_obj.GetValue("from_count");
        ToConfigId = (int)_obj.GetValue("to_config_id");
        ToCount = (int)_obj.GetValue("to_count");
    }

    public static ExchangeConfig DeserializeExchangeConfig(JToken _buf)
    {
        return new main.ExchangeConfig(_buf);
    }

    public readonly int ExchangeId;
    /// <summary>
    /// 需要的类型 必须为common id
    /// </summary>
    public readonly int FromConfigId;
    /// <summary>
    /// 需要的数量
    /// </summary>
    public readonly int FromCount;
    /// <summary>
    /// 得到的类型 必须为weapon id
    /// </summary>
    public readonly int ToConfigId;
    /// <summary>
    /// 得到的数量
    /// </summary>
    public readonly int ToCount;


    public const int __ID__ = -1045091270;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "exchangeId:" + ExchangeId + ","
        + "fromConfigId:" + FromConfigId + ","
        + "fromCount:" + FromCount + ","
        + "toConfigId:" + ToConfigId + ","
        + "toCount:" + ToCount + ","
        + "}";
    }
}
}

