
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Newtonsoft.Json.Linq;



namespace cfg.main
{

public sealed partial class GatherQuestConfig : main.ProgressQuestConfig
{
    public GatherQuestConfig(JToken _buf)  : base(_buf) 
    {
        JObject _obj = _buf as JObject;
        ItemCid = (int)_obj.GetValue("item_cid");
    }

    public static GatherQuestConfig DeserializeGatherQuestConfig(JToken _buf)
    {
        return new main.GatherQuestConfig(_buf);
    }

    public readonly int ItemCid;


    public const int __ID__ = -210538316;
    public override int GetTypeId() => __ID__;

    public override void ResolveRef(Tables tables)
    {
        base.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "questCid:" + QuestCid + ","
        + "nextQuestCid:" + NextQuestCid + ","
        + "name:" + Name + ","
        + "desc:" + Desc + ","
        + "npcOverrides:" + Luban.StringUtil.CollectionToString(NpcOverrides) + ","
        + "completeGetQuestChainCid:" + CompleteGetQuestChainCid + ","
        + "trunkNpcCids:" + Luban.StringUtil.CollectionToString(TrunkNpcCids) + ","
        + "count:" + Count + ","
        + "itemCid:" + ItemCid + ","
        + "}";
    }
}
}

