
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Newtonsoft.Json.Linq;



namespace cfg.main
{

public sealed partial class GlobalConfig : Luban.BeanBase
{
    public GlobalConfig(JToken _buf) 
    {
        JObject _obj = _buf as JObject;
        DiscMaxLevel = (int)_obj.GetValue("DiscMaxLevel");
        WeaponMaxLevel = (int)_obj.GetValue("WeaponMaxLevel");
        ChMaxEnergy = (int)_obj.GetValue("ChMaxEnergy");
        { var __json0 = _obj.GetValue("ChAttrTypes"); ChAttrTypes = new System.Collections.Generic.List<main.EAttrType>((__json0 as JArray).Count); foreach(JToken __e0 in __json0) { main.EAttrType __v0;  __v0 = (main.EAttrType)(int)__e0;  ChAttrTypes.Add(__v0); }   }
        { var __json0 = _obj.GetValue("MonsterAttrTypes"); MonsterAttrTypes = new System.Collections.Generic.List<main.EAttrType>((__json0 as JArray).Count); foreach(JToken __e0 in __json0) { main.EAttrType __v0;  __v0 = (main.EAttrType)(int)__e0;  MonsterAttrTypes.Add(__v0); }   }
    }

    public static GlobalConfig DeserializeGlobalConfig(JToken _buf)
    {
        return new main.GlobalConfig(_buf);
    }

    public readonly int DiscMaxLevel;
    public readonly int WeaponMaxLevel;
    public readonly int ChMaxEnergy;
    public readonly System.Collections.Generic.List<main.EAttrType> ChAttrTypes;
    public readonly System.Collections.Generic.List<main.EAttrType> MonsterAttrTypes;


    public const int __ID__ = 1532050170;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "DiscMaxLevel:" + DiscMaxLevel + ","
        + "WeaponMaxLevel:" + WeaponMaxLevel + ","
        + "ChMaxEnergy:" + ChMaxEnergy + ","
        + "ChAttrTypes:" + Luban.StringUtil.CollectionToString(ChAttrTypes) + ","
        + "MonsterAttrTypes:" + Luban.StringUtil.CollectionToString(MonsterAttrTypes) + ","
        + "}";
    }
}
}

