
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Newtonsoft.Json.Linq;



namespace cfg.main
{

public sealed partial class IconSticker : Luban.BeanBase
{
    public IconSticker(JToken _buf) 
    {
        JObject _obj = _buf as JObject;
        Id = (int)_obj.GetValue("id");
        Location = (string)_obj.GetValue("location");
    }

    public static IconSticker DeserializeIconSticker(JToken _buf)
    {
        return new main.IconSticker(_buf);
    }

    public readonly int Id;
    public readonly string Location;


    public const int __ID__ = 1711780271;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "location:" + Location + ","
        + "}";
    }
}
}

