
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Newtonsoft.Json.Linq;



namespace cfg.main
{

public sealed partial class MaterialItemConfig : Luban.BeanBase
{
    public MaterialItemConfig(JToken _buf) 
    {
        JObject _obj = _buf as JObject;
        Id = (int)_obj.GetValue("id");
        Name = (string)_obj.GetValue("name");
        IconLoc = (string)_obj.GetValue("icon_loc");
        Exp = (int)_obj.GetValue("exp");
    }

    public static MaterialItemConfig DeserializeMaterialItemConfig(JToken _buf)
    {
        return new main.MaterialItemConfig(_buf);
    }

    public readonly int Id;
    public readonly string Name;
    public readonly string IconLoc;
    public readonly int Exp;


    public const int __ID__ = -2041028815;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "name:" + Name + ","
        + "iconLoc:" + IconLoc + ","
        + "exp:" + Exp + ","
        + "}";
    }
}
}

