
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Newtonsoft.Json.Linq;



namespace cfg.main
{

public sealed partial class NPCOverrideConfig : Luban.BeanBase
{
    public NPCOverrideConfig(JToken _buf) 
    {
        JObject _obj = _buf as JObject;
        NpcCid = (int)_obj.GetValue("npc_cid");
        {if (_obj.TryGetValue("name", out var _j)) { Name = (string)_j; } else { Name = null; } }
        DialogueCid = (int)_obj.GetValue("dialogue_cid");
    }

    public static NPCOverrideConfig DeserializeNPCOverrideConfig(JToken _buf)
    {
        return new main.NPCOverrideConfig(_buf);
    }

    public readonly int NpcCid;
    public readonly string Name;
    public readonly int DialogueCid;


    public const int __ID__ = -730848678;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "npcCid:" + NpcCid + ","
        + "name:" + Name + ","
        + "dialogueCid:" + DialogueCid + ","
        + "}";
    }
}
}

