
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Newtonsoft.Json.Linq;



namespace cfg.main
{

public sealed partial class RewordConfig : Luban.BeanBase
{
    public RewordConfig(JToken _buf) 
    {
        JObject _obj = _buf as JObject;
        CurrencyCid = (int)_obj.GetValue("currency_cid");
        Count = (int)_obj.GetValue("count");
    }

    public static RewordConfig DeserializeRewordConfig(JToken _buf)
    {
        return new main.RewordConfig(_buf);
    }

    public readonly int CurrencyCid;
    public readonly int Count;


    public const int __ID__ = 104447892;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "currencyCid:" + CurrencyCid + ","
        + "count:" + Count + ","
        + "}";
    }
}
}

