
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Newtonsoft.Json.Linq;
using Luban;



namespace cfg.main
{

public partial class TbDiscAttrEntryAppearConfig
{
    private readonly System.Collections.Generic.Dictionary<int, main.DiscAttrEntryAppearConfig> _dataMap;
    private readonly System.Collections.Generic.List<main.DiscAttrEntryAppearConfig> _dataList;
    
    public TbDiscAttrEntryAppearConfig(JArray _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, main.DiscAttrEntryAppearConfig>();
        _dataList = new System.Collections.Generic.List<main.DiscAttrEntryAppearConfig>();
        
        foreach(JObject _ele in _buf)
        {
            main.DiscAttrEntryAppearConfig _v;
            _v = main.DiscAttrEntryAppearConfig.DeserializeDiscAttrEntryAppearConfig(_ele);
            _dataList.Add(_v);
            _dataMap.Add(_v.Pos, _v);
         }
    }


    public System.Collections.Generic.Dictionary<int, main.DiscAttrEntryAppearConfig> DataMap => _dataMap;
    public System.Collections.Generic.List<main.DiscAttrEntryAppearConfig> DataList => _dataList;

    public main.DiscAttrEntryAppearConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public main.DiscAttrEntryAppearConfig Get(int key) => _dataMap[key];
    public main.DiscAttrEntryAppearConfig this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}
}

