
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Newtonsoft.Json.Linq;
using Luban;



namespace cfg.main
{

public partial class TbDialogueGraphOptionConfig
{
    private readonly System.Collections.Generic.Dictionary<int, main.DialogueGraphOptionConfig> _dataMap;
    private readonly System.Collections.Generic.List<main.DialogueGraphOptionConfig> _dataList;
    
    public TbDialogueGraphOptionConfig(JArray _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, main.DialogueGraphOptionConfig>();
        _dataList = new System.Collections.Generic.List<main.DialogueGraphOptionConfig>();
        
        foreach(JObject _ele in _buf)
        {
            main.DialogueGraphOptionConfig _v;
            _v = main.DialogueGraphOptionConfig.DeserializeDialogueGraphOptionConfig(_ele);
            _dataList.Add(_v);
            _dataMap.Add(_v.Cid, _v);
         }
    }


    public System.Collections.Generic.Dictionary<int, main.DialogueGraphOptionConfig> DataMap => _dataMap;
    public System.Collections.Generic.List<main.DialogueGraphOptionConfig> DataList => _dataList;

    public main.DialogueGraphOptionConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public main.DialogueGraphOptionConfig Get(int key) => _dataMap[key];
    public main.DialogueGraphOptionConfig this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}
}

