
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Newtonsoft.Json.Linq;
using Luban;



namespace cfg.main
{

public partial class TbGlobalConfig
{

     private readonly main.GlobalConfig _data;

     public main.GlobalConfig Data => _data;

    public TbGlobalConfig(JArray _buf)
    {
        int n = _buf.Count;
        if (n != 1) throw new SerializationException("table mode=one, but size != 1");
        _data = main.GlobalConfig.DeserializeGlobalConfig(_buf[0]);
    }


     public int DiscMaxLevel => _data.DiscMaxLevel;
     public int WeaponMaxLevel => _data.WeaponMaxLevel;
     public int ChMaxEnergy => _data.ChMaxEnergy;
     public System.Collections.Generic.List<main.EAttrType> ChAttrTypes => _data.ChAttrTypes;
     public System.Collections.Generic.List<main.EAttrType> MonsterAttrTypes => _data.MonsterAttrTypes;
    
    public void ResolveRef(Tables tables)
    {
        _data.ResolveRef(tables);
    }



}
}

