
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Newtonsoft.Json.Linq;
using Luban;



namespace cfg.main
{

public partial class TbIconInterKnotRoleConfig
{
    private readonly System.Collections.Generic.Dictionary<int, main.IconInterKnotRoleConfig> _dataMap;
    private readonly System.Collections.Generic.List<main.IconInterKnotRoleConfig> _dataList;
    
    public TbIconInterKnotRoleConfig(JArray _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, main.IconInterKnotRoleConfig>();
        _dataList = new System.Collections.Generic.List<main.IconInterKnotRoleConfig>();
        
        foreach(JObject _ele in _buf)
        {
            main.IconInterKnotRoleConfig _v;
            _v = main.IconInterKnotRoleConfig.DeserializeIconInterKnotRoleConfig(_ele);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
         }
    }


    public System.Collections.Generic.Dictionary<int, main.IconInterKnotRoleConfig> DataMap => _dataMap;
    public System.Collections.Generic.List<main.IconInterKnotRoleConfig> DataList => _dataList;

    public main.IconInterKnotRoleConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public main.IconInterKnotRoleConfig Get(int key) => _dataMap[key];
    public main.IconInterKnotRoleConfig this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}
}

