
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Newtonsoft.Json.Linq;

namespace cfg
{
public partial class Tables
{
    public main.TbDiscConfig TbDiscConfig {get; }
    public main.TbChActionNumericConfig TbChActionNumericConfig {get; }
    public main.TbRoleConfig TbRoleConfig {get; }
    public main.TbCurrencyItemConfig TbCurrencyItemConfig {get; }
    public main.TbExchangeConfig TbExchangeConfig {get; }
    public main.TbCharacterBaseAttrConfig TbCharacterBaseAttrConfig {get; }
    public main.TbDiscAttrEntryConfig TbDiscAttrEntryConfig {get; }
    public main.TbDiscAttrEntryAppearConfig TbDiscAttrEntryAppearConfig {get; }
    public main.TbWeaponConfig TbWeaponConfig {get; }
    public main.TbGlobalConfig TbGlobalConfig {get; }
    public main.TbIconInterKnotRoleConfig TbIconInterKnotRoleConfig {get; }
    public main.TbIconSticker TbIconSticker {get; }
    public main.TbDialogueGraphSentenceConfig TbDialogueGraphSentenceConfig {get; }
    public main.TbDialogueGraphOptionConfig TbDialogueGraphOptionConfig {get; }
    public main.TbQuestChainConfig TbQuestChainConfig {get; }
    public main.TbNPCConfig TbNPCConfig {get; }
    public main.TbMonsterConfig TbMonsterConfig {get; }
    public main.TbDiscUpgradeExpConfig TbDiscUpgradeExpConfig {get; }
    public main.TbMaterialItemConfig TbMaterialItemConfig {get; }
    public main.TbAttrShowConfig TbAttrShowConfig {get; }
    public main.TbChHitNumericConfig TbChHitNumericConfig {get; }


      public Tables(System.Func<string, JArray> loader)
    {
        TbDiscConfig = new main.TbDiscConfig(loader("main_tbdiscconfig"));
        TbChActionNumericConfig = new main.TbChActionNumericConfig(loader("main_tbchactionnumericconfig"));
        TbRoleConfig = new main.TbRoleConfig(loader("main_tbroleconfig"));
        TbCurrencyItemConfig = new main.TbCurrencyItemConfig(loader("main_tbcurrencyitemconfig"));
        TbExchangeConfig = new main.TbExchangeConfig(loader("main_tbexchangeconfig"));
        TbCharacterBaseAttrConfig = new main.TbCharacterBaseAttrConfig(loader("main_tbcharacterbaseattrconfig"));
        TbDiscAttrEntryConfig = new main.TbDiscAttrEntryConfig(loader("main_tbdiscattrentryconfig"));
        TbDiscAttrEntryAppearConfig = new main.TbDiscAttrEntryAppearConfig(loader("main_tbdiscattrentryappearconfig"));
        TbWeaponConfig = new main.TbWeaponConfig(loader("main_tbweaponconfig"));
        TbGlobalConfig = new main.TbGlobalConfig(loader("main_tbglobalconfig"));
        TbIconInterKnotRoleConfig = new main.TbIconInterKnotRoleConfig(loader("main_tbiconinterknotroleconfig"));
        TbIconSticker = new main.TbIconSticker(loader("main_tbiconsticker"));
        TbDialogueGraphSentenceConfig = new main.TbDialogueGraphSentenceConfig(loader("main_tbdialoguegraphsentenceconfig"));
        TbDialogueGraphOptionConfig = new main.TbDialogueGraphOptionConfig(loader("main_tbdialoguegraphoptionconfig"));
        TbQuestChainConfig = new main.TbQuestChainConfig(loader("main_tbquestchainconfig"));
        TbNPCConfig = new main.TbNPCConfig(loader("main_tbnpcconfig"));
        TbMonsterConfig = new main.TbMonsterConfig(loader("main_tbmonsterconfig"));
        TbDiscUpgradeExpConfig = new main.TbDiscUpgradeExpConfig(loader("main_tbdiscupgradeexpconfig"));
        TbMaterialItemConfig = new main.TbMaterialItemConfig(loader("main_tbmaterialitemconfig"));
        TbAttrShowConfig = new main.TbAttrShowConfig(loader("main_tbattrshowconfig"));
        TbChHitNumericConfig = new main.TbChHitNumericConfig(loader("main_tbchhitnumericconfig"));
        ResolveRef();
    }
    
     private void ResolveRef()
    {
        TbDiscConfig.ResolveRef(this);
        TbChActionNumericConfig.ResolveRef(this);
        TbRoleConfig.ResolveRef(this);
        TbCurrencyItemConfig.ResolveRef(this);
        TbExchangeConfig.ResolveRef(this);
        TbCharacterBaseAttrConfig.ResolveRef(this);
        TbDiscAttrEntryConfig.ResolveRef(this);
        TbDiscAttrEntryAppearConfig.ResolveRef(this);
        TbWeaponConfig.ResolveRef(this);
        TbGlobalConfig.ResolveRef(this);
        TbIconInterKnotRoleConfig.ResolveRef(this);
        TbIconSticker.ResolveRef(this);
        TbDialogueGraphSentenceConfig.ResolveRef(this);
        TbDialogueGraphOptionConfig.ResolveRef(this);
        TbQuestChainConfig.ResolveRef(this);
        TbNPCConfig.ResolveRef(this);
        TbMonsterConfig.ResolveRef(this);
        TbDiscUpgradeExpConfig.ResolveRef(this);
        TbMaterialItemConfig.ResolveRef(this);
        TbAttrShowConfig.ResolveRef(this);
        TbChHitNumericConfig.ResolveRef(this);
    }
}

}

